### ISSUE TITLE
Modify Stripe plugin to support latest Invoices for Fixed pricing plan

### ISSUE THREAD

**Issue by NivethGoutham** [wso2-extensions/wso2-am-stripe-plugin#41]
**Description:**
The fix for this newer version needs to be merged with the latest Stripe plugin

**Affected Product Version:**
APIM 4.1.0

**Comment by IsuruMaduranga** [comment]
Hi,

We released v1.3.3 of strip plugin ( https://github.com/wso2-extensions/wso2-am-stripe-plugin/releases/tag/v1.3.3 ) fixing this issue

Thanks,
Isuru
